In [1]:
import numpy as np
import tensorflow as tf

In [40]:
x1 = [1,2,1,1,0,2,1]
cnt1 = 3
x2 = [0,3,1,3,0,2,1]
cnt2 = 4

In [3]:
session = tf.Session()

In [4]:
y = tf.one_hot(x, cnt)
session.run(y)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [27]:
Z = tf.placeholder(tf.int32, [None, 1])
Y = tf.one_hot(Z, 3)
Y = tf.reshape(Y, [-1, 3])
X = np.array(x)
X = X.reshape([-1, 1])
session.run(Y, feed_dict={Z: X})

Tensor("Placeholder_6:0", shape=(?, 1), dtype=int32)
Tensor("Reshape_1:0", shape=(?, 3), dtype=float32)
[[1]
 [2]
 [1]
 [1]
 [0]
 [2]
 [1]] Tensor("Placeholder_6:0", shape=(?, 1), dtype=int32)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [41]:
z1 = np.zeros([len(x1), cnt1])
z1[np.arange(len(x1)), x1] = 1
z1

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [42]:
z2 = np.zeros([len(x2), cnt2])
z2[np.arange(len(x2)), x2] = 1
z2

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [43]:
np.concatenate([z1, z2], axis=1)

array([[0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0.]])

In [44]:
z1.(z2, axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'